project:
  type: website
  output-dir: docs

website:
  title: "Things with Maps"
  repo-url: https://github.com/MattBixley/condes_tutorial
  issue-url: https://github.com/MattBixley/condes_tutorial/issues
  repo-actions: edit
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2024, Matt Bixley"
 
# Navbar settings   
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: pages/condes_tutorial/condes_tutorial.qmd
        text: Condes Tutorial
      - href: pages/rogaine_planning/rogaine_planning.qmd
        text: Rogaine Planning
      - href: pages/course_planning/course_planning.qmd
        text: Course Planning
      - href: pages/rogaine_planning/maps.qmd
        text: Maps
    right:
      - icon: github
        href: https://github.com
  
  page-navigation: true

# formatting
format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual
